name: update

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: 'true'

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Install git-secret
        uses: Kingmidas74/git-secret-github-action@latest
      - name: Reveal secrets
        run: git secret reveal
      - name: Install openvpn
        run: sudo apt install openvpn
      - name: Write vpn secrets to file
        env:
          VPN_SECRET: ${{secrets.VPN_SECRET}}
        run: 'echo "$VPN_SECRET" > vpn_secrets.conf'
        shell: bash
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      - name: Connect to VPN
        run: |
          sudo openvpn --config .github/workflows/hu-berlin.ovpn --auth-user-pass vpn_secrets.conf &&
          sleep 20
      - name: Run ML pipeline
        run: |
          poetry run jupyter nbconvert --to notebook --execute Detection\ model\ \(logistic\ regression\)/Detection\ model\ \(Logistic\ regression\).ipynb
      - name: Update plots
        uses: test-room-7/action-update-file@v1
        with:
          file-path: Detection\ model\ \(logistic\ regression\)/*.png
          commit-msg: Update resources
          github-token: ${{ secrets.PUSH_TOKEN }}
